### PR TITLE
[qt] Give exact fix for OSV-2020-902

### PR DESCRIPTION
**Pull request by rlohning**

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
thanks!

**Comment by oliverchang** [comment]
> Is there something like "-type: FIX" for the added link?

Yes! The list is here: https://github.com/ossf/osv-schema/blob/main/schema.md#references-field

**Comment by rlohning** [comment]
Hi Oliver,

thank you for your improvements.

I see that the list of affected versions was already updated. I'm surprised though that "v5.15.2" is not in the list. I could reproduce the issue with that version and it's branch does not contain the fix. Did anything confuse the bot?

Cheers,
Robert

**Comment by oliverchang** [comment]
Thanks for pointing this out Robert! I've opened https://github.com/google/osv/issues/203 to investigate this.

**Comment by oliverchang** [comment]
This should be fixed by https://github.com/google/osv/pull/204. It'll likely get merged and deployed next week, and I'll rerun the analysis on all qt entries.

**Comment by rlohning** [comment]
Thank you!

**Comment by rlohning** [comment]
In case this is related, please have a look at https://github.com/google/oss-fuzz-vulns/pull/9#issuecomment-898281069

**Comment by oliverchang** [comment]
https://github.com/google/oss-fuzz-vulns/commit/fb452b4877f85dcfc950c0f1dc9598efe2c19707 now includes 5.15.2

**Pull request merged**
