### PR TITLE
[qt] Fix OSV-2021-1121

### PR DESCRIPTION
**Pull request by rlohning**
Remove unrelated patch from different repository

### CODE REVIEW

**Comment by rlohning** [comment]
The listed versions will be updated automatically, won't they?

**Comment by oliverchang** [comment]
> The listed versions will be updated automatically, won't they?

To regenerate them from scratch, we need to empty the `versions` array. I just did that!

**Review by oliverchang — APPROVED** [review]

**Comment by rlohning** [comment]
Thank you!

**Comment by rlohning** [comment]
...and the wrong id was added again, presumably by some script. Anything I/you/we can do about that?

**Comment by oliverchang** [comment]
> ...and the wrong id was added again, presumably by some script. Anything I/you/we can do about that?

hmm, this is based on our automated cherry pick detection. seems like there's a bug in there somewhere causing this unrelated commit to be added. I'll file an infra bug for this. 

Does this negatively impact the impacted version determination?

**Pull request merged**
